from __future__ import annotations

import json
import pickle
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from sentence_transformers import SentenceTransformer
from sklearn.mixture import GaussianMixture
from starlette.responses import FileResponse

from .cache import SemanticCache
from .vector_index import DenseVectorIndex


BASE_DIR = Path(__file__).resolve().parent.parent
ARTIFACT_DIR = BASE_DIR / "artifacts"
FRONTEND_DIST = BASE_DIR / "frontend" / "dist"


class QueryRequest(BaseModel):
    query: str


class QueryResponse(BaseModel):
    query: str
    cache_hit: bool
    matched_query: Optional[str]
    similarity_score: float
    result: str
    dominant_cluster: int


class CacheStatsResponse(BaseModel):
    total_entries: int
    hit_count: int
    miss_count: int
    hit_rate: float
    similarity_threshold: float


def load_artifacts():
    """
    Load artifacts generated by scripts/prepare_index.py:
    - config.json
    - doc_texts.jsonl
    - doc_embeddings.npy
    - gmm.pkl
    - doc_cluster_probs.npy
    We load the sentence-transformer model by name at runtime. [web:14]
    """
    config_path = ARTIFACT_DIR / "config.json"
    texts_path = ARTIFACT_DIR / "doc_texts.jsonl"
    embeddings_path = ARTIFACT_DIR / "doc_embeddings.npy"
    gmm_path = ARTIFACT_DIR / "gmm.pkl"
    cluster_probs_path = ARTIFACT_DIR / "doc_cluster_probs.npy"

    if not all(
        p.exists()
        for p in [config_path, texts_path, embeddings_path, gmm_path, cluster_probs_path]
    ):
        raise RuntimeError(
            "Artifacts are missing. Run scripts/prepare_index.py first."
        )

    with config_path.open("r", encoding="utf-8") as f:
        config = json.load(f)

    docs: List[Dict[str, Any]] = []
    with texts_path.open("r", encoding="utf-8") as f:
        for line in f:
            docs.append(json.loads(line))

    embeddings = np.load(embeddings_path)
    cluster_probs = np.load(cluster_probs_path)

    with gmm_path.open("rb") as f:
        gmm: GaussianMixture = pickle.load(f)

    embedder = SentenceTransformer(config["embedding_model"])
    index = DenseVectorIndex(embeddings)

    if embeddings.shape[1] != config["embedding_dim"]:
        raise RuntimeError("Embedding dimension mismatch between config and stored data.")

    return {
        "config": config,
        "docs": docs,
        "embeddings": embeddings,
        "cluster_probs": cluster_probs,
        "gmm": gmm,
        "embedder": embedder,
        "index": index,
    }


def make_result_string(
    query: str,
    sims: np.ndarray,
    doc_indices: np.ndarray,
    docs: List[Dict[str, Any]],
    max_chars_per_doc: int = 220,
) -> str:
    """
    Compose a simple textual result from top-k documents.
    """
    lines = [f"Query: {query}", "", "Top matches:"]

    for rank, (sim, idx) in enumerate(zip(sims, doc_indices), start=1):
        d = docs[int(idx)]
        snippet = d["text"][:max_chars_per_doc].replace("\n", " ")
        label = d.get("label_name", "unknown")
        lines.append(
            f"{rank}. [sim={sim:.3f}] [{label}] {snippet}..."
        )

    return "\n".join(lines)


app = FastAPI(title="Trademarkia Semantic Search Demo")


@app.on_event("startup")
def startup_event():
    artifacts = load_artifacts()
    app.state.config = artifacts["config"]
    app.state.docs = artifacts["docs"]
    app.state.embeddings = artifacts["embeddings"]
    app.state.cluster_probs = artifacts["cluster_probs"]
    app.state.gmm = artifacts["gmm"]
    app.state.embedder = artifacts["embedder"]
    app.state.index = artifacts["index"]

    embedding_dim = app.state.embeddings.shape[1]
    num_clusters = app.state.gmm.n_components

    similarity_threshold = float(app.state.config.get("similarity_threshold", 0.85))

    app.state.cache = SemanticCache(
        embedding_dim=embedding_dim,
        num_clusters=num_clusters,
        similarity_threshold=similarity_threshold,
        max_entries_per_cluster=1000,
        top_m_clusters=3,
    )

    print(
        f"Loaded artifacts: {len(app.state.docs)} docs, "
        f"{num_clusters} clusters, dim={embedding_dim}."
    )


@app.post("/query", response_model=QueryResponse)
def query_endpoint(payload: QueryRequest):
    q = payload.query.strip()
    if not q:
        raise HTTPException(status_code=400, detail="Query must be non-empty.")

    embedder: SentenceTransformer = app.state.embedder
    gmm: GaussianMixture = app.state.gmm
    index: DenseVectorIndex = app.state.index
    docs: List[Dict[str, Any]] = app.state.docs
    cache: SemanticCache = app.state.cache

    q_vec = embedder.encode(
        [q],
        convert_to_numpy=True,
        normalize_embeddings=True,
    )[0].astype("float32")

    cluster_dist = gmm.predict_proba(q_vec.reshape(1, -1))[0].astype("float32")

    cache_hit, entry, sim, dominant_cluster = cache.lookup(q_vec, cluster_dist)

    if cache_hit and entry is not None:
        return QueryResponse(
            query=q,
            cache_hit=True,
            matched_query=entry.query,
            similarity_score=sim,
            result=entry.result,
            dominant_cluster=dominant_cluster,
        )

    sims, idxs = index.search(q_vec, top_k=5)
    result_str = make_result_string(q, sims, idxs, docs)

    cache.insert(
        query=q,
        embedding=q_vec,
        cluster_distribution=cluster_dist,
        result=result_str,
    )

    return QueryResponse(
        query=q,
        cache_hit=False,
        matched_query=q,
        similarity_score=1.0,
        result=result_str,
        dominant_cluster=int(np.argmax(cluster_dist)),
    )


@app.get("/cache/stats", response_model=CacheStatsResponse)
def cache_stats_endpoint():
    cache: SemanticCache = app.state.cache
    stats = cache.stats()
    return CacheStatsResponse(
        total_entries=stats["total_entries"],
        hit_count=stats["hit_count"],
        miss_count=stats["miss_count"],
        hit_rate=stats["hit_rate"],
        similarity_threshold=stats["similarity_threshold"],
    )


@app.delete("/cache")
def cache_delete_endpoint():
    cache: SemanticCache = app.state.cache
    cache.flush()
    return {"status": "ok", "message": "Semantic cache flushed."}


# --------- Static frontend (optional single-origin deployment) ---------

if FRONTEND_DIST.exists():
    app.mount(
        "/assets",
        StaticFiles(directory=FRONTEND_DIST / "assets"),
        name="assets",
    )

    @app.get("/{full_path:path}")
    async def serve_spa(full_path: str):
        """
        Serve the React SPA for any non-API route.
        API routes (/query, /cache/...) take precedence because they are
        registered explicitly above. [web:22]
        """
        index_path = FRONTEND_DIST / "index.html"
        if index_path.exists():
            return FileResponse(index_path)
        raise HTTPException(status_code=404, detail="Frontend not built.")
